version: '3.6'

services:
  test:
    image: nginx
    restart: always
    volumes:
      - "./:/usr/share/nginx/html"
    environment:
      # NGINX-PROXY ENVIRONMENT VARIABLES: UPDATE ME
      - VIRTUAL_HOST=test.igorleonovich.com 
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=test.igorleonovich.com 
      - LETSENCRYPT_EMAIL=mail@igorleonovich.com
      # /END NGINX-PROXY ENVIRONMENT VARIABLES
    expose:
      - 80

networks:
  default:
    external:
      name: nginx-proxy
